exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(EC944Dff) rgba(523B29ff) 45deg
    col.inactive_border = rgba(59301Fff) rgba(A46748ff) 45deg
}

group {
    col.border_active = rgba(EC944Dff) rgba(523B29ff) 45deg
    col.border_inactive = rgba(59301Fcc) rgba(A46748cc) 45deg
    col.border_locked_active = rgba(090908ff) rgba(0E1011ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
