exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(CBCFCAff) rgba(315229ff) 45deg
    col.inactive_border = rgba(20202Cff) rgba(334462ff) 45deg
}

group {
    col.border_active = rgba(CBCFCAff) rgba(315229ff) 45deg
    col.border_inactive = rgba(20202Ccc) rgba(334462cc) 45deg
    col.border_locked_active = rgba(141313ff) rgba(080808ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
