exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(CABEB3ff) rgba(523C29ff) 45deg
    col.inactive_border = rgba(090A0Bff) rgba(342F29ff) 45deg
}

group {
    col.border_active = rgba(CABEB3ff) rgba(523C29ff) 45deg
    col.border_inactive = rgba(090A0Bcc) rgba(342F29cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(0A0A0Bff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
