# ~/.config/starship.toml


################################################
# Inserts a blank line between shell prompts
add_newline = true

################################################
# Change the default prompt format
# format = """\
# [╭╴](bold white)(238)$env_var\
# $all[╰─](bold white)(238)\
# $character"""
format = """\
$all\
$env_var\
$character"""

################################################
[time]
disabled = true
format = '[\($time\)]($style) '
time_format = '%H:%M'

################################################
[cmd_duration]
min_time = 100

################################################
# Change the default prompt characters
[character]
# 
# ❯
success_symbol = '[❯](bold green)'
error_symbol = '[❯](red)'

################################################
[os]
disabled = true
format = '[$symbol](bold black)'

[os.symbols]
Windows = ""
Linux = ""
Arch = ""


################################################
# Shows the username: Admin
[username]
style_user = "bold white"
style_root = "bold black"
format = "[$user]($style) "
disabled = false             # disable in powershell
show_always = true

################################################
# Shows the hostname: %USER%  
[hostname]
ssh_only = false
format = '[$hostname](purple) '
trim_at = "."
disabled = true

################################################
# Shows the directory: C:\  
[directory]
truncation_symbol = "…/"
truncation_length = 4
style = "bold yellow"
home_symbol = "~"
read_only_style = "197"
truncate_to_repo = false
read_only = "  "
# format = "[$path]($style)[$read_only]($read_only_style) "
format = "at [$path]($style)[$read_only]($read_only_style) "

################################################
[git_branch]
symbol = "󰊢 "
format = "on [$symbol$branch]($style) "
# truncation_length = 4
# truncation_symbol = "…/"
style = "bold green"

################################################
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = " 🏳 "
up_to_date = "  "
untracked = "  "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " 󰏗 "
modified = "  "
staged = '[++\($count\)](green)'
renamed = " 󰖷 "
deleted = "  "

################################################
[docker_context]
format = "via [🐋 $context](bold blue) "

################################################
[python]
symbol = "󰌠 "
python_binary = "python3"

################################################
[nodejs]
format = "via [󰎙 $version](bold green) "
disabled = false

################################################
[solidity]
format = "via [ $version](bold green) "

################################################
[ruby]
format = "via [ $version]($style) "

################################################
[kubernetes]
format = 'on [ $context\($namespace\)](bold purple) '
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

